# Site settings
title: ReCAD
email: recad.engineers@gmail.com
description: "Desgin and BIM Solutions."
twitter_username: jekyllrb
github_username:  jekyll
baseurl: "/freelancer-theme"

# Build settings
markdown: kramdown
permalink: pretty
